#!/bin/sh

for target; do :; done
args=`echo "$@" | sed 's/\.plugin$/.cmxa/'`

ocamlbuild \
    -use-ocamlfind \
    -classic-display \
    -syntax camlp4o \
    -pkg bap \
    -pkg bap.plugins \
    -pkg core_kernel \
    -pkg sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax \
    -pkg bin_prot.syntax \
    -tag thread \
    -tag debug \
    -tag annot \
    -tag bin_annot \
    -tag short_paths \
    -cflags "-w A-4-33-40-41-42-43-34-44" \
    -cflags -strict-sequence \
    $args
result=$?

name=`basename $target .plugin 2>/dev/null`
source="_build/$name.cmxa"

if [ -f "$source" ]; then
    CMD=`grep -A1 "Target: $name.cmxa" _build/_log | grep -v "Target" | sed 's/.cmxa/.cmxs/' | sed 's/-a/-shared/'`
    cd _build
    $CMD
    cp "$name.cmxs" "../$target"
    cd ..
    chmod a-x $target
fi

exit $result
