# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
  end
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
sudo apt-get update
sudo apt-get install curl make git m4 libcap-dev gcc unzip --yes

echo "" | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)

yes | opam init --compiler=4.05.0 --disable-sandboxing
eval $(opam env)

opam install depext --yes
opam depext bap  -i --yes

sudo apt-get install python-pip --yes
sudo pip install bap
SHELL
end
