name: Archlinux

on:
  schedule:
    - cron: "0 0 * * TUE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build on Archlinux
        uses: docker/build-push-action@v2
        with:
          push: false
          file: docker/archlinux/Dockerfile
