name: Bionic
on:
  - push

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@master

     - name: Build on Ubuntu Bionic
       uses: docker/build-push-action@v1
       with:
         push: false
         dockerfile: docker/ubuntu/bionic/Dockerfile
