name: Publish Docker
on:
  - push
#  schedule:
#    - cron: '0 18 * * *' # Every day at 18:00 UTC


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Publish Ubuntu image to Registry
      uses: docker/build-push-action@v1
      with:
        repository: binaryanalysisplatform/bap
        tags: latest
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile
