# tests all packages, including bap-extra
name: full
run-name: Testing everything in ${{ github.ref }}

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BAP_LOG_DIR: $HOME/log
      OPAMRETRES: 8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ghidra
        uses: ./.github/actions/install-ghidra

      - name: Install Dejagnu
        run: |
          sudo apt-get update -y
          sudo apt-get install dejagnu -y

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.x
          dune-cache: true
          opam-disable-sandboxing: true
          opam-repositories: |
            default: git+https://github.com/ocaml/opam-repository.git
            bap: git+https://github.com/BinaryAnalysisPlatform/opam-repository#testing


      - name: Install BAP Dependencies
        run: opam install . --deps-only

      - name: Configure BAP
        run: opam exec -- ocaml tools/configure.ml --with-llvm-config=$(opam var conf-bap-llvm:config)

      - name: Build BAP
        run: opam exec -- dune build

      - name: Install BAP
        run: opam exec -- dune install

      - name: Run Unit Tests
        run: opam exec -- dune test --display=short

      - name: Run Functional Tests
        run: opam exec -- make check

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: bap-log-full
          path: ~/.local/state/bap

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: fun-tests-log-full
          path: |
            testsuite/*.log
            testsuite/logs
