name: builds-bap-on-many-os
on:
  - push

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@master

     - name: Build BAP
       uses: docker/build-push-action@v1
       with:
         push: false
         dockerfile: docker/opensuse/Dockerfile