name: builds-bap-on-many-os
on:
  - push

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@master

     - name: Build on Alpine
       uses: docker/build-push-action@v1
       with:
         push: false
         dockerfile: docker/alpine/Dockerfile

     - name: Build on Archlinux
       uses: docker/build-push-action@v1
       with:
         push: false
         dockerfile: docker/archlinux/Dockerfile

     - name: Build on Debian Testing
       uses: docker/build-push-action@v1
       with:
         push: false
         dockerfile: docker/debian/testing/Dockerfile

     - name: Build on Fedora
       uses: docker/build-push-action@v1
       with:
         push: false
         dockerfile: docker/fedora/Dockerfile

     - name: Build on Ubuntu Bionic
       uses: docker/build-push-action@v1
       with:
         push: false
         dockerfile: docker/ubuntu/bionic/Dockerfile
