name: Publish the Latest Release to Docker
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Ubuntu image to Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: binaryanalysisplatform/bap:2.4.0
          file: docker/2.4.0/Dockerfile
