name: release

on:
  schedule:
    - cron: "0 0 * * SAT" # every Saturday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPAMJOBS: 2
      OPAMRETRES: 8
      VERSION: 2.6.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.4.14.2+flambda
          dune-cache: true

      - name: Cache Ghidra
        id: cache-ghidra
        uses: actions/cache@v4
        with:
          path: /usr/share/ghidra
          key: ${{ runner.os }}-ghidra

      - name: Build and Install Ghidra
        if: steps.cache-ghidras.outputs.cache-hit != 'true'
        run: sudo sh ./tools/install-ghidra.sh

      - name: Add the testing Repository
        run: opam repo add bap git+https://github.com/BinaryAnalysisPlatform/opam-repository#testing

      - name: Build deb packages
        run: ./tools/release.sh ${{ env.VERSION }}

        # caution: this action overwrite the tag and deletes
        # releases that are associated with it
      - name: Create a new prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ env.VERSION }}-alpha
          prerelease: true
          title: "Development Build"
          files: bap/*
