name: release

on:
  schedule:
    - cron: "0 0 * * SAT" # every Saturday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      OPAMJOBS: 2
      OPAMRETRES: 8
      VERSION: 2.4.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.4.11.2+flambda
          dune-cache: true

      - name: Install Ghidra
        run: |
          sudo add-apt-repository ppa:ivg/ghidra -y
          sudo apt-get install libghidra-dev -y
          sudo apt-get install libghidra-data -y

      - name: Add the testing Repository
        run: opam repo add bap git://github.com/BinaryAnalysisPlatform/opam-repository#testing
      - name: Build deb packages
        run: ./tools/release.sh ${{ env.VERSION }}

        # caution: this action overwrite the tag and deletes
        # releases that are associated with it
      - name: Create a new prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ env.VERSION }}-alpha
          prerelease: true
          title: "Development Build"
          files: bap/*
